zodiac_compatibility = {
    "Aries": {
        "Aries": {"compatibility": 50, "attributes": ["Highly volatile"]},
        "Taurus": {"compatibility": 38, "attributes": ["Nothing in common"]},
        "Gemini": {"compatibility": 83, "attributes": ["Mutual understanding", "Great sexual chemistry"]},
        "Cancer": {"compatibility": 42, "attributes": ["Low commitment"]},
        "Leo": {"compatibility": 97, "attributes": ["Harmonious", "Great sexual chemistry"]},
        "Virgo": {"compatibility": 63, "attributes": ["Good work combination"]},
        "Libra": {"compatibility": 85, "attributes": ["Natural partners", "Great sexual chemistry"]},
        "Scorpio": {"compatibility": 50, "attributes": ["Highly volatile"]},
        "Sagittarius": {"compatibility": 93, "attributes": ["Great sexual chemistry", "Mutual understanding"]},
        "Capricorn": {"compatibility": 47, "attributes": ["Nothing in common"]},
        "Aquarius": {"compatibility": 78, "attributes": ["Mutual understanding"]},
        "Pisces": {"compatibility": 67, "attributes": ["Harmonious"]}
    },
    "Taurus": {
        "Aries": {"compatibility": 38, "attributes": ["Nothing in common"]},
        "Taurus": {"compatibility": 65, "attributes": ["Good work combination"]},
        "Gemini": {"compatibility": 33, "attributes": ["Nothing in common"]},
        "Cancer": {"compatibility": 97, "attributes": ["Harmonious", "Natural partners"]},
        "Leo": {"compatibility": 73, "attributes": ["Great sexual chemistry"]},
        "Virgo": {"compatibility": 90, "attributes": ["Natural partners", "Good work combination"]},
        "Libra": {"compatibility": 65, "attributes": ["Good work combination"]},
        "Scorpio": {"compatibility": 88, "attributes": ["Great sexual chemistry"]},
        "Sagittarius": {"compatibility": 30, "attributes": ["Nothing in common"]},
        "Capricorn": {"compatibility": 98, "attributes": ["Harmonious"]},
        "Aquarius": {"compatibility": 58, "attributes": ["Low commitment"]},
        "Pisces": {"compatibility": 85, "attributes": ["Natural partners", "Great sexual chemistry"]}
    },
    "Gemini": {
        "Aries": {"compatibility": 83, "attributes": ["Mutual understanding", "Great sexual chemistry"]},
        "Taurus": {"compatibility": 33, "attributes": ["Nothing in common"]},
        "Gemini": {"compatibility": 60, "attributes": ["Good work combination"]},
        "Cancer": {"compatibility": 65, "attributes": ["Low commitment"]},
        "Leo": {"compatibility": 88, "attributes": ["Mutual understanding"]},
        "Virgo": {"compatibility": 68, "attributes": ["Good work combination"]},
        "Libra": {"compatibility": 93, "attributes": ["Great sexual chemistry", "Natural partners"]},
        "Scorpio": {"compatibility": 28, "attributes": ["Nothing in common"]},
        "Sagittarius": {"compatibility": 60, "attributes": ["Mutual understanding"]},
        "Capricorn": {"compatibility": 68, "attributes": ["Good work combination"]},
        "Aquarius": {"compatibility": 85, "attributes": ["Great sexual chemistry", "Harmonious"]},
        "Pisces": {"compatibility": 53, "attributes": ["Low commitment"]}
    },
    "Cancer": {
        "Aries": {"compatibility": 42, "attributes": ["Low commitment"]},
        "Taurus": {"compatibility": 97, "attributes": ["Harmonious", "Natural partners"]},
        "Gemini": {"compatibility": 65, "attributes": ["Low commitment"]},
        "Cancer": {"compatibility": 75, "attributes": ["Good work combination"]},
        "Leo": {"compatibility": 35, "attributes": ["Nothing in common"]},
        "Virgo": {"compatibility": 90, "attributes": ["Natural partners"]},
        "Libra": {"compatibility": 43, "attributes": ["Low commitment"]},
        "Scorpio": {"compatibility": 94, "attributes": ["Natural partners", "Great sexual chemistry"]},
        "Sagittarius": {"compatibility": 48, "attributes": ["Nothing in common"]},
        "Capricorn": {"compatibility": 83, "attributes": ["Great sexual chemistry"]},
        "Aquarius": {"compatibility": 27, "attributes": ["Nothing in common"]},
        "Pisces": {"compatibility": 98, "attributes": ["Harmonious"]}
    },
    "Leo": {
        "Aries": {"compatibility": 97, "attributes": ["Harmonious", "Great sexual chemistry"]},
        "Taurus": {"compatibility": 73, "attributes": ["Great sexual chemistry"]},
        "Gemini": {"compatibility": 88, "attributes": ["Mutual understanding"]},
        "Cancer": {"compatibility": 35, "attributes": ["Nothing in common"]},
        "Leo": {"compatibility": 97, "attributes": ["Harmonious"]},
        "Virgo": {"compatibility": 45, "attributes": ["Nothing in common"]},
        "Libra": {"compatibility": 97, "attributes": ["Natural partners", "Great sexual chemistry"]},
        "Scorpio": {"compatibility": 58, "attributes": ["Low commitment"]},
        "Sagittarius": {"compatibility": 93, "attributes": ["Great sexual chemistry", "Mutual understanding"]},
        "Capricorn": {"compatibility": 35, "attributes": ["Nothing in common"]},
        "Aquarius": {"compatibility": 68, "attributes": ["Mutual understanding"]},
        "Pisces": {"compatibility": 38, "attributes": ["Nothing in common"]}
    },
    "Virgo": {
        "Aries": {"compatibility": 63, "attributes": ["Good work combination"]},
        "Taurus": {"compatibility": 90, "attributes": ["Natural partners", "Good work combination"]},
        "Gemini": {"compatibility": 68, "attributes": ["Good work combination"]},
        "Cancer": {"compatibility": 90, "attributes": ["Natural partners"]},
        "Leo": {"compatibility": 45, "attributes": ["Nothing in common"]},
        "Virgo": {"compatibility": 90, "attributes": ["Good work combination"]},
        "Libra": {"compatibility": 68, "attributes": ["Good work combination"]},
        "Scorpio": {"compatibility": 88, "attributes": ["Great sexual chemistry"]},
        "Sagittarius": {"compatibility": 28, "attributes": ["Nothing in common"]},
        "Capricorn": {"compatibility": 95, "attributes": ["Natural partners"]},
        "Aquarius": {"compatibility": 30, "attributes": ["Nothing in common"]},
        "Pisces": {"compatibility": 88, "attributes": ["Great sexual chemistry"]}
    },
    "Libra": {
        "Aries": {"compatibility": 85, "attributes": ["Natural partners", "Great sexual chemistry"]},
        "Taurus": {"compatibility": 65, "attributes": ["Good work combination"]},
        "Gemini": {"compatibility": 93, "attributes": ["Great sexual chemistry", "Natural partners"]},
        "Cancer": {"compatibility": 43, "attributes": ["Low commitment"]},
        "Leo": {"compatibility": 97, "attributes": ["Natural partners", "Great sexual chemistry"]},
        "Virgo": {"compatibility": 68, "attributes": ["Good work combination"]},
        "Libra": {"compatibility": 75, "attributes": ["Harmonious"]},
        "Scorpio": {"compatibility": 35, "attributes": ["Highly volatile"]},
        "Sagittarius": {"compatibility": 75, "attributes": ["Great sexual chemistry"]},
        "Capricorn": {"compatibility": 55, "attributes": ["Low commitment"]},
        "Aquarius": {"compatibility": 90, "attributes": ["Harmonious"]},
        "Pisces": {"compatibility": 68, "attributes": ["Good work combination"]}
    },
    "Scorpio": {
        "Aries": {"compatibility": 50, "attributes": ["Highly volatile"]},
        "Taurus": {"compatibility": 88, "attributes": ["Great sexual chemistry"]},
        "Gemini": {"compatibility": 28, "attributes": ["Nothing in common"]},
        "Cancer": {"compatibility": 94, "attributes": ["Natural partners", "Great sexual chemistry"]},
        "Leo": {"compatibility": 58, "attributes": ["Low commitment"]},
        "Virgo": {"compatibility": 88, "attributes": ["Great sexual chemistry"]},
        "Libra": {"compatibility": 35, "attributes": ["Highly volatile"]},
        "Scorpio": {"compatibility": 95, "attributes": ["Natural partners", "Great sexual chemistry"]},
        "Sagittarius": {"compatibility": 28, "attributes": ["Nothing in common"]},
        "Capricorn": {"compatibility": 95, "attributes": ["Natural partners"]},
        "Aquarius": {"compatibility": 73, "attributes": ["Low commitment"]},
        "Pisces": {"compatibility": 97, "attributes": ["Harmonious", "Great sexual chemistry"]}
    },
    "Sagittarius": {
        "Aries": {"compatibility": 93, "attributes": ["Great sexual chemistry", "Mutual understanding"]},
        "Taurus": {"compatibility": 30, "attributes": ["Nothing in common"]},
        "Gemini": {"compatibility": 60, "attributes": ["Mutual understanding"]},
        "Cancer": {"compatibility": 48, "attributes": ["Nothing in common"]},
        "Leo": {"compatibility": 93, "attributes": ["Great sexual chemistry", "Mutual understanding"]},
        "Virgo": {"compatibility": 28, "attributes": ["Nothing in common"]},
        "Libra": {"compatibility": 75, "attributes": ["Great sexual chemistry"]},
        "Scorpio": {"compatibility": 28, "attributes": ["Nothing in common"]},
        "Sagittarius": {"compatibility": 60, "attributes": ["Mutual understanding"]},
        "Capricorn": {"compatibility": 45, "attributes": ["Nothing in common"]},
        "Aquarius": {"compatibility": 60, "attributes": ["Mutual understanding"]},
        "Pisces": {"compatibility": 63, "attributes": ["Harmonious"]}
    },
    "Capricorn": {
        "Aries": {"compatibility": 47, "attributes": ["Nothing in common"]},
        "Taurus": {"compatibility": 98, "attributes": ["Harmonious"]},
        "Gemini": {"compatibility": 68, "attributes": ["Good work combination"]},
        "Cancer": {"compatibility": 83, "attributes": ["Great sexual chemistry"]},
        "Leo": {"compatibility": 35, "attributes": ["Nothing in common"]},
        "Virgo": {"compatibility": 95, "attributes": ["Natural partners"]},
        "Libra": {"compatibility": 55, "attributes": ["Low commitment"]},
        "Scorpio": {"compatibility": 95, "attributes": ["Natural partners"]},
        "Sagittarius": {"compatibility": 45, "attributes": ["Nothing in common"]},
        "Capricorn": {"compatibility": 60, "attributes": ["Good work combination"]},
        "Aquarius": {"compatibility": 75, "attributes": ["Mutual understanding"]},
        "Pisces": {"compatibility": 88, "attributes": ["Great sexual chemistry"]}
    },
    "Aquarius": {
        "Aries": {"compatibility": 78, "attributes": ["Mutual understanding"]},
        "Taurus": {"compatibility": 58, "attributes": ["Low commitment"]},
        "Gemini": {"compatibility": 85, "attributes": ["Great sexual chemistry", "Harmonious"]},
        "Cancer": {"compatibility": 27, "attributes": ["Nothing in common"]},
        "Leo": {"compatibility": 68, "attributes": ["Mutual understanding"]},
        "Virgo": {"compatibility": 30, "attributes": ["Nothing in common"]},
        "Libra": {"compatibility": 90, "attributes": ["Harmonious"]},
        "Scorpio": {"compatibility": 73, "attributes": ["Low commitment"]},
        "Sagittarius": {"compatibility": 60, "attributes": ["Mutual understanding"]},
        "Capricorn": {"compatibility": 75, "attributes": ["Mutual understanding"]},
        "Aquarius": {"compatibility": 68, "attributes": ["Good work combination"]},
        "Pisces": {"compatibility": 45, "attributes": ["Nothing in common"]}
    },
    "Pisces": {
        "Aries": {"compatibility": 67, "attributes": ["Harmonious"]},
        "Taurus": {"compatibility": 85, "attributes": ["Natural partners", "Great sexual chemistry"]},
        "Gemini": {"compatibility": 53, "attributes": ["Low commitment"]},
        "Cancer": {"compatibility": 98, "attributes": ["Harmonious"]},
        "Leo": {"compatibility": 38, "attributes": ["Nothing in common"]},
        "Virgo": {"compatibility": 88, "attributes": ["Great sexual chemistry"]},
        "Libra": {"compatibility": 68, "attributes": ["Good work combination"]},
        "Scorpio": {"compatibility": 97, "attributes": ["Harmonious", "Great sexual chemistry"]},
        "Sagittarius": {"compatibility": 63, "attributes": ["Harmonious"]},
        "Capricorn": {"compatibility": 88, "attributes": ["Great sexual chemistry"]},
        "Aquarius": {"compatibility": 45, "attributes": ["Nothing in common"]},
        "Pisces": {"compatibility": 60, "attributes": ["Good work combination"]}
    }
}

zodiac_last_day = {
    "Aries": "April 19",
    "Taurus": "May 20",
    "Gemini": "June 20",
    "Cancer": "July 22",
    "Leo": "August 22",
    "Virgo": "September 22",
    "Libra": "October 22",
    "Scorpio": "November 21",
    "Sagittarius": "December 21",
    "Capricorn": "January 19",
    "Aquarius": "February 18",
    "Pisces": "March 20"
}
